analytics.account={"id"\:1681274,"name"\:"Gtech","uuid"\:"1abf0881-7362-44be-973e-b0ae3c9eb900","domain"\:"ac-1681274"}
analytics.integration.enable=true
analytics.onpremise.enable=true
analytics.onpremise.organization=null
analytics.onpremise.server=https\://testops.katalon.io
analytics.project={"id"\:3473519,"name"\:"OrangeHRM","teamId"\:3459300,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3495263,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:3459300,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
onpremise.email=agung.priyadi@gtech.digital
onpremise.password=rCSJ9pV1oNQlNp9OJTP8ZQ\=\=
